# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20151216_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('brief', models.TextField(verbose_name='Brief')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('headimg', models.ImageField(upload_to=b'', verbose_name='Head image')),
                ('published', models.BooleanField(verbose_name='Published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.UserProfile', verbose_name='Author')),
            ],
        ),
    ]
