# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0005_auto_20151223_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=45, verbose_name='Identifier')),
                ('uuid', models.CharField(max_length=45, verbose_name='UUID')),
                ('major', models.IntegerField(verbose_name='Major')),
                ('minor', models.IntegerField(verbose_name='Minor')),
                ('comment', models.CharField(max_length=45, verbose_name='Comment')),
                ('stick_on', models.ManyToManyField(to='vehicle.Bus', verbose_name='Stick on')),
            ],
        ),
    ]
