# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='mac',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='comment',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Comment'),
        ),
    ]
