# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0003_auto_20160101_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='stick_on',
            field=models.ManyToManyField(blank=True, to='vehicle.Bus', verbose_name='Stick on'),
        ),
    ]
