# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0004_auto_20160101_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
            preserve_default=False,
        ),
    ]
