# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0005_beacon_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User id')),
                ('bid', models.CharField(max_length=45, verbose_name='\u6c7d\u8f66\u552f\u4e00\u7f16\u53f7')),
                ('event', models.IntegerField(choices=[(0, 'enter'), (1, 'leave'), (2, 'stay')], verbose_name='event')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
