# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0006_beaconcheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beaconcheckin',
            name='event',
        ),
        migrations.RemoveField(
            model_name='beaconcheckin',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='emission_reduction',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u51cf\u6392\u6811\u91cf'),
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='energy_saving_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Energy saving amount'),
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='energy_saving_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Energy saving money'),
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update time'),
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='off_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Off time'),
        ),
        migrations.AddField(
            model_name='beaconcheckin',
            name='on_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='On time'),
        ),
    ]
