# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavingEnergyPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User id')),
                ('timestamp', models.DateField()),
                ('energy_saving_amount', models.IntegerField(blank=True, null=True, verbose_name='Energy saving amount')),
                ('energy_saving_money', models.IntegerField(blank=True, null=True, verbose_name='Energy saving money')),
                ('emission_reduction', models.IntegerField(blank=True, null=True, verbose_name='\u51cf\u6392\u6811\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='UserSavingEnergyPerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User id')),
                ('energy_saving_amount', models.IntegerField(blank=True, null=True, verbose_name='Energy saving amount')),
                ('energy_saving_money', models.IntegerField(blank=True, null=True, verbose_name='Energy saving money')),
                ('emission_reduction', models.IntegerField(blank=True, null=True, verbose_name='\u51cf\u6392\u6811\u91cf')),
                ('timestamp', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
    ]
