# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingenergyperday',
            name='total_milage',
            field=models.FloatField(blank=True, null=True, verbose_name='\u603b\u91cc\u7a0b'),
        ),
        migrations.AddField(
            model_name='usersavingenergypermonth',
            name='total_milage',
            field=models.FloatField(blank=True, null=True, verbose_name='\u603b\u91cc\u7a0b'),
        ),
    ]
