# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=45)),
                ('plate_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, '\u9759\u6b62'), (1, '\u7eaf\u7535\u52a8'), (2, '\u6df7\u5408\u52a8\u529b'), (3, '\u884c\u8f66\u5145\u7535'), (4, '\u5236\u52a8\u56de\u9988')])),
                ('gear', models.IntegerField(choices=[(0, 'P'), (1, 'R'), (2, 'N'), (3, 'D')])),
                ('failure_info', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Bus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
