# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_mileagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
