# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20160101_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdata',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='\u8f66\u901f'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='emission_reduction',
            field=models.FloatField(blank=True, null=True, verbose_name='\u51cf\u6392\u6811\u91cf'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='energy_saving_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy saving amount'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='energy_saving_money',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy saving money'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u7535\u6d41'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u7535\u538b'),
        ),
        migrations.AlterField(
            model_name='gasdata',
            name='bottle_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='\u6c22\u6c14\u74f6\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='gasdata',
            name='remain',
            field=models.FloatField(blank=True, null=True, verbose_name='\u6c22\u6c14\u4f59\u91cf'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='remain',
            field=models.FloatField(blank=True, null=True, verbose_name='\u7eed\u9a76\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='section',
            field=models.FloatField(blank=True, null=True, verbose_name='\u5206\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='\u603b\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor current'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor speed'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor temperature'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor torque'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor voltage'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u7535\u6d41'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='remain',
            field=models.FloatField(blank=True, null=True, verbose_name='Battery left'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u7535\u538b'),
        ),
    ]
