# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20160111_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdata',
            name='failure_info',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6545\u969c\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='gear',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6863\u4f4d'),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='speed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8f66\u901f'),
        ),
        migrations.AlterField(
            model_name='busdata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8f66\u8f86\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='emission_reduction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u51cf\u6392\u6811\u91cf'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='energy_saving_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Energy saving amount'),
        ),
        migrations.AlterField(
            model_name='energysavingdata',
            name='energy_saving_money',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Energy saving money'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='current',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u7535\u6d41'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='fuelcelldata',
            name='voltage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u71c3\u6599\u7535\u6c60\u7535\u538b'),
        ),
        migrations.AlterField(
            model_name='gasdata',
            name='bottle_temp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6c22\u6c14\u74f6\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='gasdata',
            name='remain',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6c22\u6c14\u4f59\u91cf'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='remain',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7eed\u9a76\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5206\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='mileagedata',
            name='total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u603b\u91cc\u7a0b'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='current',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor current'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='speed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor speed'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor temperature'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='torque',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor torque'),
        ),
        migrations.AlterField(
            model_name='motordata',
            name='voltage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor voltage'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='current',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u7535\u6d41'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='remain',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Battery left'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='temp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='powerbatterydata',
            name='voltage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u52a8\u529b\u7535\u6c60\u7535\u538b'),
        ),
    ]
