# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 03:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='phone number must be 11 digits', regex='\\d{11}')])),
                ('gender', models.IntegerField(blank=True, choices=[(1, '\u7537'), (2, '\u5973')], null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
            ],
        ),
    ]
