# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 04:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='phone number must be 11 digits', regex='^\\d{11}$')]),
        ),
    ]
