# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20151230_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
